---
# tasks file for apigee-opdk-setup-mirror-nginx
- block:
  - name: Create mirror.properties
    file:
      path: '{{ mirror_file }}'
      state: touch
      owner: apigee
      group: apigee

  - name: Add line
    lineinfile:
      dest: '{{ mirror_file }}'
      line: '{{ item }}'
      owner: apigee
      group: apigee
    with_items:
    - conf_apigee_mirror_listen_port={{ apigee_mirror_listen_port }}
    - conf_apigee_mirror_server_name={{ apigee_mirror_server_name }}

  become: yes

- name: Ensure that apigee-mirror is installed
  shell: "{{ apigee_service }} apigee-mirror install"
  args:
    creates: "{{ apigee_home }}/apigee-mirror/lib/actions/nginxconfig"

- name: Install mirror server
  shell: "{{ apigee_service }} apigee-mirror nginxconfig"
  args:
    removes: "{{ apigee_home }}/apigee-mirror/lib/actions/nginxconfig"
  notify:
    - Nginx restart

#- name: Add nginx credentials
#  lineinfile:
#    backrefs: yes
#    dest: /etc/environment
#    regexp: "({{ item.attribute }}).*"
#    line: '{{ item.attribute }}{{ item.value }}'
#  with_items:
#  - { attribute: 'export MIRROR_USERNAME=', value: '{{ apigee_repo_user | default(default_apigee_repo_user) }}' }
#  - { attribute: 'export MIRROR_PASSWORD=', value: '{{ apigee_repo_password | default(default_apigee_repo_password) }}' }
